#!/usr/bin/env bash
# Script that installs Nginx server and redirects /redirect_me
apt-get -y update
apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
sed -i "/server_name _;/ a\\\trewrite ^/redirect_me https://www.alxafrica.com permanent;" /etc/nginx/sites-available/default
service nginx start
