#!/usr/bin/env bash
# This script is displaying "Best School" 10 times, substituting
# messages at the 4th and 8th lines
m=0; while (( m < 10 )); do
if (( m == 3 )); then echo 'bad luck'
elif (( m == 7 )); then echo 'good luck'
else echo 'Best School'; fi
((m++)); done
unset m
