#!/usr/bin/env bash
# This script is displaying integers from 1-20, adding messages at 4,5,17
m=1
while (( m < 21 )); do
echo $m
case $m in
    4 )
	echo 'bad luck from China';;
    9 )
	echo 'bad luck from Japan';;
    17 )
	echo 'bad luck from Italy';;
    esac
((m++)); done
unset m
